server:
  port: 8770
spring:
  application:
    name: admin-server
  boot:
    admin:
      discovery:
        ignored-services: admin-server
eureka:
  instance:
    preferIpAddress: true
    hostname: 192.168.0.24
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.0.24:8761/eureka,http://192.168.0.24:8762/eureka