server:
  port: 8771
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: first_provider_id
          uri: lb://first-provider
          predicates:
            - Path=/first-provider/**
          filters:
            - name: CircuitBreaker
              args:
                name: myCircuitBreaker
                fallbackUri: forward:/inCaseOfFailureUseThis
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 2
                key-resolver: "#{@ipKeyResolver}"
      discovery:
        locator:
          enabled: false #开启从注册中心动态创建路由的功能
          lower-case-service-id: true #使用小写服务名，默认是大写
  redis:
    host: 192.168.0.200
    port: 6379
    password:

eureka:
  instance:
    preferIpAddress: true
    hostname: 192.168.0.24
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.0.24:8761/eureka,http://192.168.0.24:8762/eureka